# Generated by Django 5.1.6 on 2026-03-15 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('registration_open', 'Registration Open'), ('active', 'Active'), ('judging', 'Judging'), ('finished', 'Finished'), ('archived', 'Archived')], db_index=True, max_length=32)),
                ('event_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], db_index=True, max_length=16)),
                ('participation_type', models.CharField(choices=[('team', 'Team'), ('individual', 'Individual')], db_index=True, max_length=16)),
                ('industry', models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('robotics', 'Robotics'), ('cybersecurity', 'Cybersecurity')], db_index=True, max_length=32)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('mixed', 'Mixed')], db_index=True, max_length=32)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('total_rounds', models.PositiveIntegerField(default=1)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('is_live_stream_enabled', models.BooleanField(default=False)),
                ('is_online_now', models.BooleanField(default=False)),
                ('registration_open', models.BooleanField(default=False)),
                ('submissions_open', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('trending_score', models.FloatField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('timer_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCompetitionWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_live', models.BooleanField(default=True)),
                ('watch_rounds', models.BooleanField(default=True)),
                ('watch_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='landing.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'competition')},
            },
        ),
        migrations.CreateModel(
            name='UserSavedCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='landing.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'competition')},
            },
        ),
    ]
